name: ${project.artifactId}
main: autosaveworld.core.AutoSaveWorld
version: ${project.version}
api-version: 1.16
author: _Shevchik_
load: STARTUP
softdepend: [Vault, Essentials, WorldEdit, WorldGuard, GriefPrevemtion, Towny]
libraries:
  - commons-codec:commons-codec:1.15
  - commons-net:commons-net:3.8.0
  - com.jcraft:jsch:0.1.55
  - com.google.auth:google-auth-library-oauth2-http:1.8.1
  - com.google.apis:google-api-services-drive:v3-rev20220508-1.32.1

commands:
  autosaveworld:
    description: All AutoSaveWorld commands
    aliases: asw
    usage: Use /asw help  to show all commands available in plugin
  autobackup:
    description: AutoSaveWorld /asw backup command
    aliases: backup
    usage: Use /backup to run AutoBackup
  autopurge:
    description: AutoSaveWorld /asw purge command
    aliases: purge
    usage: Use /purge to run AutoPurge